development:
  adapter: postgresql
  encoding: unicode
  database: run_development
  pool: 5
  host: localhost
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: run_test
  pool: 5
  host: localhost
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: run_staging
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: run_production
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *test